### ISSUE TITLE
getAddressBalance [RPCError: Method not found]

### ISSUE THREAD

**Issue by raineroviir** [qtumproject/qtumd-rpc#1]
```
[2017-12-31T02:39:13.499Z] error: [AddressBalanceService] Update Error { RPCError: Method not found
    at Qtum._wrapRPCError (/Users/raineroviir/qtumcorenode/mytestnode/node_modules/qtumcore-node/lib/services/qtumd.js:549:13)
    at /Users/raineroviir/qtumcorenode/mytestnode/node_modules/qtumcore-node/lib/services/qtumd.js:1211:30
```

I have tracked the rpc error down to the rpc method: `getAddressBalance`. 

I see `getAddressBalance` listed in the rpc client as a method. So what is going on here?  This error is preventing the insight-api from logging the transactions and balances of each account.

**Comment by changshoumeng** [comment]
I have this problem, too. How did you solve it?
